blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.saedgewell.net
    about: For documentation and tutorials.
  - name: Administrative Requests (licenses, etc.)
    url: https://saedgewell.net/contact
    about: Please report administrative requests here.