export const shadcnEntries = [
  'src/shadcn/accordion.tsx',
  'src/shadcn/alert-dialog.tsx',
  'src/shadcn/avatar.tsx',
  'src/shadcn/button.tsx',
  'src/shadcn/calendar.tsx',
  'src/shadcn/card.tsx',
  'src/shadcn/checkbox.tsx',
  'src/shadcn/command.tsx',
  'src/shadcn/data-table.tsx',
  'src/shadcn/dialog.tsx',
  'src/shadcn/dropdown-menu.tsx',
  'src/shadcn/navigation-menu.tsx',
  'src/shadcn/form.tsx',
  'src/shadcn/input.tsx',
  'src/shadcn/label.tsx',
  'src/shadcn/popover.tsx',
  'src/shadcn/scroll-area.tsx',
  'src/shadcn/select.tsx',
  'src/shadcn/sheet.tsx',
  'src/shadcn/table.tsx',
  'src/shadcn/tabs.tsx',
  'src/shadcn/tooltip.tsx',
  'src/shadcn/sonner.tsx',
  'src/shadcn/heading.tsx',
  'src/shadcn/alert.tsx',
  'src/shadcn/badge.tsx',
  'src/shadcn/radio-group.tsx',
  'src/shadcn/separator.tsx',
  'src/shadcn/input-otp.tsx',
  'src/shadcn/textarea.tsx',
  'src/shadcn/switch.tsx',
  'src/shadcn/breadcrumb.tsx',
  'src/shadcn/chart.tsx',
  'src/shadcn/skeleton.tsx',
  'src/shadcn/sidebar.tsx',
  'src/shadcn/collapsible.tsx',
];

export const makerkitEntries = [
  'src/makerkit/if.tsx',
  'src/makerkit/trans.tsx',
  'src/makerkit/sidebar.tsx',
  'src/makerkit/navigation-config.schema.ts',
  'src/makerkit/bordered-navigation-menu.tsx',
  'src/makerkit/spinner.tsx',
  'src/makerkit/page.tsx',
  'src/makerkit/image-uploader.tsx',
  'src/makerkit/global-loader.tsx',
  'src/makerkit/auth-change-listener.tsx',
  'src/makerkit/loading-overlay.tsx',
  'src/makerkit/profile-avatar.tsx',
  'src/makerkit/mode-toggle.tsx',
  'src/makerkit/data-table.tsx',
  'src/makerkit/language-selector.tsx',
  'src/makerkit/stepper.tsx',
  'src/makerkit/cookie-banner.tsx',
  'src/makerkit/card-button.tsx',
  'src/makerkit/version-updater.tsx',
  'src/makerkit/multi-step-form.tsx',
  'src/makerkit/app-breadcrumbs.tsx',
  'src/makerkit/empty-state.tsx',
  'src/makerkit/marketing/index.tsx',
];

export const utilEntries = ['src/lib/utils/index.ts'];

export const allEntries = [
  ...shadcnEntries,
  ...makerkitEntries,
  ...utilEntries,
];
