export const shadcnExports = {
  './accordion': './src/shadcn/accordion.tsx',
  './alert-dialog': './src/shadcn/alert-dialog.tsx',
  './avatar': './src/shadcn/avatar.tsx',
  './button': './src/shadcn/button.tsx',
  './calendar': './src/shadcn/calendar.tsx',
  './card': './src/shadcn/card.tsx',
  './checkbox': './src/shadcn/checkbox.tsx',
  './command': './src/shadcn/command.tsx',
  './data-table': './src/shadcn/data-table.tsx',
  './dialog': './src/shadcn/dialog.tsx',
  './dropdown-menu': './src/shadcn/dropdown-menu.tsx',
  './navigation-menu': './src/shadcn/navigation-menu.tsx',
  './form': './src/shadcn/form.tsx',
  './input': './src/shadcn/input.tsx',
  './label': './src/shadcn/label.tsx',
  './popover': './src/shadcn/popover.tsx',
  './scroll-area': './src/shadcn/scroll-area.tsx',
  './select': './src/shadcn/select.tsx',
  './sheet': './src/shadcn/sheet.tsx',
  './table': './src/shadcn/table.tsx',
  './tabs': './src/shadcn/tabs.tsx',
  './tooltip': './src/shadcn/tooltip.tsx',
  './sonner': './src/shadcn/sonner.tsx',
  './heading': './src/shadcn/heading.tsx',
  './alert': './src/shadcn/alert.tsx',
  './badge': './src/shadcn/badge.tsx',
  './radio-group': './src/shadcn/radio-group.tsx',
  './separator': './src/shadcn/separator.tsx',
  './input-otp': './src/shadcn/input-otp.tsx',
  './textarea': './src/shadcn/textarea.tsx',
  './switch': './src/shadcn/switch.tsx',
  './breadcrumb': './src/shadcn/breadcrumb.tsx',
  './chart': './src/shadcn/chart.tsx',
  './skeleton': './src/shadcn/skeleton.tsx',
  './shadcn-sidebar': './src/shadcn/sidebar.tsx',
  './collapsible': './src/shadcn/collapsible.tsx',
} as const;

export const makerkitExports = {
  './if': './src/makerkit/if.tsx',
  './trans': './src/makerkit/trans.tsx',
  './sidebar': './src/makerkit/sidebar.tsx',
  './navigation-schema': './src/makerkit/navigation-config.schema.ts',
  './bordered-navigation-menu': './src/makerkit/bordered-navigation-menu.tsx',
  './spinner': './src/makerkit/spinner.tsx',
  './page': './src/makerkit/page.tsx',
  './image-uploader': './src/makerkit/image-uploader.tsx',
  './global-loader': './src/makerkit/global-loader.tsx',
  './auth-change-listener': './src/makerkit/auth-change-listener.tsx',
  './loading-overlay': './src/makerkit/loading-overlay.tsx',
  './profile-avatar': './src/makerkit/profile-avatar.tsx',
  './mode-toggle': './src/makerkit/mode-toggle.tsx',
  './enhanced-data-table': './src/makerkit/data-table.tsx',
  './language-selector': './src/makerkit/language-selector.tsx',
  './stepper': './src/makerkit/stepper.tsx',
  './cookie-banner': './src/makerkit/cookie-banner.tsx',
  './card-button': './src/makerkit/card-button.tsx',
  './version-updater': './src/makerkit/version-updater.tsx',
  './multi-step-form': './src/makerkit/multi-step-form.tsx',
  './app-breadcrumbs': './src/makerkit/app-breadcrumbs.tsx',
  './empty-state': './src/makerkit/empty-state.tsx',
  './marketing': './src/makerkit/marketing/index.tsx',
} as const;

export const utilExports = {
  './utils': './src/lib/utils/index.ts',
} as const;

export const allExports = {
  ...shadcnExports,
  ...makerkitExports,
  ...utilExports,
} as const;
