export const shadcnEntries = [
  'src/shadcn/accordion/index.tsx',
  'src/shadcn/alert-dialog/index.tsx',
  'src/shadcn/alert/index.tsx',
  'src/shadcn/avatar/index.tsx',
  'src/shadcn/badge/index.tsx',
  'src/shadcn/breadcrumb/index.tsx',
  'src/shadcn/button/index.tsx',
  'src/shadcn/calendar/index.tsx',
  'src/shadcn/card/index.tsx',
  'src/shadcn/checkbox/index.tsx',
  'src/shadcn/collapsible/index.tsx',
  'src/shadcn/command/index.tsx',
  'src/shadcn/data-table/index.tsx',
  'src/shadcn/dialog/index.tsx',
  'src/shadcn/drawer/index.tsx',
  'src/shadcn/dropdown-menu/index.tsx',
  'src/shadcn/form/index.tsx',
  'src/shadcn/input/index.tsx',
  'src/shadcn/interactive-hover-button/index.tsx',
  'src/shadcn/label/index.tsx',
  'src/shadcn/navigation-menu/index.tsx',
  'src/shadcn/number-ticker/index.tsx',
  'src/shadcn/popover/index.tsx',
  'src/shadcn/progress/index.tsx',
  'src/shadcn/radio-group/index.tsx',
  'src/shadcn/scroll-area/index.tsx',
  'src/shadcn/select/index.tsx',
  'src/shadcn/separator/index.tsx',
  'src/shadcn/sheet/index.tsx',
  'src/shadcn/sidebar/index.tsx',
  'src/shadcn/skeleton/index.tsx',
  'src/shadcn/slider/index.tsx',
  'src/shadcn/sonner/index.tsx',
  'src/shadcn/switch/index.tsx',
  'src/shadcn/table/index.tsx',
  'src/shadcn/tabs/index.tsx',
  'src/shadcn/textarea/index.tsx',
  'src/shadcn/tooltip/index.tsx',
];

export const makerkitEntries = [
  'src/makerkit/if.tsx',
  'src/makerkit/trans.tsx',
  'src/makerkit/sidebar.tsx',
  'src/makerkit/navigation-config.schema.ts',
  'src/makerkit/bordered-navigation-menu.tsx',
  'src/makerkit/spinner.tsx',
  'src/makerkit/page.tsx',
  'src/makerkit/image-uploader.tsx',
  'src/makerkit/global-loader.tsx',
  'src/makerkit/auth-change-listener.tsx',
  'src/makerkit/loading-overlay.tsx',
  'src/makerkit/profile-avatar.tsx',
  'src/makerkit/mode-toggle.tsx',
  'src/makerkit/data-table.tsx',
  'src/makerkit/language-selector.tsx',
  'src/makerkit/stepper.tsx',
  'src/makerkit/cookie-banner.tsx',
  'src/makerkit/card-button.tsx',
  'src/makerkit/version-updater.tsx',
  'src/makerkit/multi-step-form.tsx',
  'src/makerkit/app-breadcrumbs.tsx',
  'src/makerkit/empty-state.tsx',
  'src/makerkit/marketing/index.tsx',
];

export const customEntries = [
  'src/custom/page-header.tsx',
  'src/custom/section-title.tsx',
  'src/custom/basic-hero.tsx',
  'src/custom/back-link.tsx',
  'src/custom/responsive-dialog.tsx',
];

export const magicuiEntries = [
  'src/magicui/animated-circular-progress-bar/index.tsx',
  'src/magicui/animated-grid-pattern/index.tsx',
  'src/magicui/aurora-text/index.tsx',
  'src/magicui/bento-grid/index.tsx',
  'src/magicui/dot-pattern/index.tsx',
  'src/magicui/flickering-grid/index.tsx',
  'src/magicui/flip-text/index.tsx',
  'src/magicui/galaxy-3d/index.tsx',
  'src/magicui/gear-background/index.tsx',
  'src/magicui/grid-pattern/index.tsx',
  'src/magicui/interest-pattern/index.tsx',
  'src/magicui/kagome-pattern/index.tsx',
  'src/magicui/linear-rotate/index.tsx',
  'src/magicui/magic-card/index.tsx',
  'src/magicui/marquee/index.tsx',
  'src/magicui/meteors/index.tsx',
  'src/magicui/neon-gradient-card/index.tsx',
  'src/magicui/note-pattern/index.tsx',
  'src/magicui/orbit-animation/index.tsx',
  'src/magicui/orbiting-circles/index.tsx',
  'src/magicui/particles/index.tsx',
  'src/magicui/ripple/index.tsx',
  'src/magicui/scroll-fade-text/index.tsx',
  'src/magicui/scroll-text-animation/index.tsx',
  'src/magicui/seigaiha-pattern/index.tsx',
  'src/magicui/shimmer-button/index.tsx',
  'src/magicui/shippo-pattern/index.tsx',
  'src/magicui/spinning-text/index.tsx',
  'src/magicui/wave-background/index.tsx',
];

export const utilEntries = ['src/lib/utils/index.ts'];

export const allEntries = [
  ...shadcnEntries,
  ...makerkitEntries,
  ...utilEntries,
];
